spring.application.name=weightop
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

spring.datasource.url=jdbc:postgresql://localhost:5432/comments_db
spring.datasource.username=comment_user
spring.datasource.password=comment_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false